version: "3.3"
   
services:
  python-env:
    container_name: python-script-publish-twb
    build:
      context: .
      dockerfile: Dockerfile_Dev
    command: python publish-twb.py
    volumes:
      - .:/code
